import { Poppins } from "next/font/google";
import "./globals.css";

// Correctly configure the Poppins font with desired weights
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Edunify",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
